name: Publish to GH Pages - Sreenivas
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/master'
        with:
          ref: gh-pages
          path: built-site

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          cp -R out/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          ls -l ${GITHUB_WORKSPACE}/built-site
