name: Publish to GH Pages - Sreenivas
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R out/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'cooolbabu'
          git config user.email 'cooolbabu@yahoo.com'
          git commit -m 'Updated site'
          git push
